# Keep GitHub Actions up to date automatically
version: 2
updates:
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "ci"
      include: "scope"
    reviewers:
      - "thsfranca"
    open-pull-requests-limit: 5

  # Go modules updates  
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"  
      day: "monday"
      time: "10:00"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "thsfranca"
    open-pull-requests-limit: 5
