name: Debug Path Changes

on:
  pull_request:
    branches: [ main ]

jobs:
  debug-what-changed:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Debug changed files with paths-filter
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          go-files:
            - '**/*.go'
            - 'go.mod'
            - 'go.sum'
            - 'tools/grammar/**'
          makefile-changes:
            - 'Makefile'
          non-go-files:
            - 'vscode-extension/**'
            - 'fugo/**'
            - 'docs/**'
            - 'examples/**/*.fugo'
            - '**/*.md'
          all-files:
            - '**'
    
    - name: Print debug information
      run: |
        echo "=== PATHS FILTER DEBUG ==="
        echo "Go files changed: ${{ steps.changes.outputs.go-files }}"
        echo "Makefile changed: ${{ steps.changes.outputs.makefile-changes }}"
        echo "Non-Go files changed: ${{ steps.changes.outputs.non-go-files }}"
        echo "Any files changed: ${{ steps.changes.outputs.all-files }}"
        echo ""
        echo "=== FILES THAT MATCH FILTERS ==="
        echo "Go files list: ${{ steps.changes.outputs.go-files_files }}"
        echo "Makefile files: ${{ steps.changes.outputs.makefile-changes_files }}"
        echo "Non-Go files list: ${{ steps.changes.outputs.non-go-files_files }}"
        echo ""
        echo "=== SMART MAKEFILE ANALYSIS ==="
        if [[ "${{ steps.changes.outputs.makefile-changes }}" == "true" ]]; then
          echo "Makefile was changed, analyzing for Go relevance..."
          if git diff origin/main...HEAD Makefile | grep -E "(go (build|test|mod|generate)|GOPATH|GOOS|GOARCH|\.go|antlr.*-Dlanguage=Go)" > /dev/null; then
            echo "✅ Makefile changes are Go-related"
            echo "Go-related patterns found:"
            git diff origin/main...HEAD Makefile | grep -E "(go (build|test|mod|generate)|GOPATH|GOOS|GOARCH|\.go|antlr.*-Dlanguage=Go)" || true
          else
            echo "⚠️ Makefile changes appear to be non-Go related"
          fi
        else
          echo "No Makefile changes detected"
        fi
        echo ""
        echo "=== GITHUB EVENT CONTEXT ==="
        echo "Event name: ${{ github.event_name }}"
        echo "Ref: ${{ github.ref }}"
        echo "Base ref: ${{ github.base_ref }}"
        echo "Head ref: ${{ github.head_ref }}"