---
name: Vex Go Parser Generation

on:
  push:
    branches: [main]
    paths:
      - 'tools/grammar/**'
  pull_request:
    branches: [main]
    paths:
      - 'tools/grammar/**'
  # Run weekly to catch platform-specific issues
  schedule:
    - cron: '0 6 * * 1' # Monday 6 AM UTC

env:
  ANTLR_VERSION: '4.13.1'
  GO_VERSION: '1.21'

jobs:
  test-go-parser-generation:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # Platform-specific ANTLR setup
      - name: Install ANTLR (Linux/macOS)
        if: runner.os != 'Windows'
        env:
          ANTLR_VERSION: ${{ env.ANTLR_VERSION }}
        run: .github/scripts/parser/install-antlr-unix.sh

      - name: Install ANTLR (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        env:
          ANTLR_VERSION: ${{ env.ANTLR_VERSION }}
        run: .github/scripts/parser/install-antlr-windows.ps1

      # Go runtime setup
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      # Generate Go parser
      - name: Generate Go parser (Linux/macOS)
        if: runner.os != 'Windows'
        run: .github/scripts/parser/generate-go-parser-unix.sh

      - name: Generate Go parser (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: .github/scripts/parser/generate-go-parser-windows.ps1

      # Verify generated Go files
      - name: Verify generated Go files
        run: .github/scripts/parser/verify-generated-files.sh
        shell: bash

      # Test Go compilation
      - name: Test Go compilation
        run: .github/scripts/parser/test-compilation.sh

      # Upload artifacts for debugging
      - name: Upload generated Go parser
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: go-parser-${{ matrix.os }}
          path: tools/gen/go/
          retention-days: 7

  # Summary job
  go-parser-summary:
    runs-on: ubuntu-latest
    needs: test-go-parser-generation
    if: always()
    steps:
      - name: Check results
        run: .github/scripts/parser/generate-summary.sh "${{ needs.test-go-parser-generation.result }}"

