---
name: Vex Grammar & Examples Validation

on:
  push:
    branches: [main]
    paths:
      - 'tools/grammar/**'
      - 'examples/**/*.vx'
  pull_request:
    branches: [main]
    paths:
      - 'tools/grammar/**'
      - 'examples/**/*.vx'

env:
  ANTLR_VERSION: '4.13.1'

jobs:
  validate-grammar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # Cache ANTLR installation
      - name: Cache ANTLR
        id: antlr-cache
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/antlr.jar
          key: ${{ runner.os }}-antlr-${{ env.ANTLR_VERSION }}

      - name: Install ANTLR
        if: steps.antlr-cache.outputs.cache-hit != 'true'
        env:
          ANTLR_VERSION: ${{ env.ANTLR_VERSION }}
        run: .github/scripts/ci/install-antlr.sh

      - name: Setup ANTLR binary
        run: .github/scripts/ci/setup-antlr-binary.sh

      - name: Validate grammar syntax
        run: .github/scripts/grammar/validate-syntax.sh

      - name: Generate Go test parser
        run: .github/scripts/grammar/generate-test-parser.sh

      - name: Test example files with Go parser
        run: .github/scripts/grammar/test-examples.sh

      - name: Validate grammar completeness
        run: .github/scripts/grammar/validate-completeness.sh

