---
name: Vex Grammar & Examples Validation

on:
  push:
    branches: [main]
    paths:
      - 'tools/grammar/**'
      - 'examples/**/*.vx'
  pull_request:
    branches: [main]
    paths:
      - 'tools/grammar/**'
      - 'examples/**/*.vx'

env:
  ANTLR_VERSION: '4.13.1'

jobs:
  validate-grammar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # Cache ANTLR installation
      - name: Cache ANTLR
        id: antlr-cache
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/antlr.jar
          key: ${{ runner.os }}-antlr-${{ env.ANTLR_VERSION }}

      - name: Install ANTLR
        if: steps.antlr-cache.outputs.cache-hit != 'true'
        run: |
          wget https://www.antlr.org/download/antlr-${{ env.ANTLR_VERSION }}-complete.jar -O /tmp/antlr.jar
          sudo mv /tmp/antlr.jar /usr/local/lib/

      - name: Setup ANTLR binary
        run: |
          echo '#!/bin/bash' | sudo tee /usr/local/bin/antlr4
          echo 'java -jar /usr/local/lib/antlr.jar "$@"' | sudo tee -a /usr/local/bin/antlr4
          sudo chmod +x /usr/local/bin/antlr4

      - name: Validate grammar syntax
        run: |
          cd tools/grammar
          antlr4 -Dlanguage=Go Vex.g4 -o /tmp/grammar-test

      - name: Generate Go test parser
        run: |
          cd tools/grammar
          antlr4 -Dlanguage=Go -listener -visitor Vex.g4 -o /tmp/vex-parser

      - name: Test example files with Go parser
        run: |
          echo "🔨 Setting up grammar validator..."
          
          # Create parser subdirectory and copy generated files there
          mkdir -p tools/grammar-validator/parser
          cp /tmp/vex-parser/*.go tools/grammar-validator/parser/
          
          # Build the grammar validator tool
          cd tools/grammar-validator
          go mod download
          go build -o grammar-validator .
          
          # Test valid example files (must pass)
          echo "🧪 Testing valid example files..."
          if [ -d "$GITHUB_WORKSPACE/examples/valid" ]; then
            VALID_FILES=$(find $GITHUB_WORKSPACE/examples/valid -name "*.vx")
            if [ -n "$VALID_FILES" ]; then
              ./grammar-validator --valid $VALID_FILES
            else
              echo "⚠️ No valid .vx files found"
            fi
          fi
          
          # Test invalid example files (must fail)
          echo "🧪 Testing invalid example files..."
          if [ -d "$GITHUB_WORKSPACE/examples/invalid" ]; then
            INVALID_FILES=$(find $GITHUB_WORKSPACE/examples/invalid -name "*.vx")
            if [ -n "$INVALID_FILES" ]; then
              ./grammar-validator --invalid $INVALID_FILES
            else
              echo "⚠️ No invalid .vx files found"
            fi
          fi

      - name: Validate grammar completeness
        run: |
          echo "🔍 Checking grammar completeness..."
          
          # Check for common language constructs that should be supported
          GRAMMAR_FILE="tools/grammar/Vex.g4"
          
          echo "Checking for required grammar rules..."
          
          # Check if basic rules exist (account for multi-line definitions)
          if ! grep -q "^sp" "$GRAMMAR_FILE"; then
            echo "❌ Missing root rule 'sp'"
            exit 1
          fi
          
          if ! grep -q "^list" "$GRAMMAR_FILE"; then
            echo "❌ Missing 'list' rule"
            exit 1
          fi
          
          if ! grep -q "SYMBOL" "$GRAMMAR_FILE"; then
            echo "❌ Missing SYMBOL token"
            exit 1
          fi
          
          if ! grep -q "STRING" "$GRAMMAR_FILE"; then
            echo "❌ Missing STRING token"
            exit 1
          fi
          
          echo "✅ Grammar contains required basic rules"
          echo "✅ Grammar validation completed successfully"

