---
name: Vex Grammar & Examples Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  ANTLR_VERSION: '4.13.1'

jobs:
  # Always runs - detects if we need to run validation
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      grammar-changed: ${{ steps.changes.outputs.grammar-changed }}
      needs-validation: ${{ steps.decision.outputs.needs-validation }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Check for relevant changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            grammar-changed:
              - 'tools/grammar/**'
              - 'examples/**/*.vx'
              
      - name: Decide if validation needed
        id: decision
        run: .github/scripts/validation/decide-validation-needed.sh "${{ steps.changes.outputs.grammar-changed }}"

  validate-grammar:
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.needs-validation == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # Cache ANTLR installation
      - name: Cache ANTLR
        id: antlr-cache
        uses: actions/cache@v4
        with:
          path: /usr/local/lib/antlr.jar
          key: ${{ runner.os }}-antlr-${{ env.ANTLR_VERSION }}

      - name: Install ANTLR
        if: steps.antlr-cache.outputs.cache-hit != 'true'
        env:
          ANTLR_VERSION: ${{ env.ANTLR_VERSION }}
        run: .github/scripts/ci/install-antlr.sh

      - name: Setup ANTLR binary
        run: .github/scripts/ci/setup-antlr-binary.sh

      - name: Validate grammar syntax
        run: .github/scripts/grammar/validate-syntax.sh

      - name: Generate Go test parser
        run: .github/scripts/grammar/generate-test-parser.sh

      - name: Test example files with Go parser
        run: .github/scripts/grammar/test-examples.sh

      - name: Validate grammar completeness
        run: .github/scripts/grammar/validate-completeness.sh

  # Gateway job - ALWAYS runs and reports status (make this required in branch protection)
  grammar-validation-required:
    runs-on: ubuntu-latest
    needs: [detect-changes, validate-grammar]
    if: always()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Evaluate results
        run: .github/scripts/validation/evaluate-grammar-results.sh "${{ needs.detect-changes.outputs.grammar-changed }}" "${{ needs.detect-changes.outputs.needs-validation }}" "${{ needs.validate-grammar.result }}"

