---
name: Release Drafter

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    paths-ignore:
      - 'vscode-extension/**'

permissions:
  contents: read

jobs:
  update_release_draft:
    name: "Vex Language Release Draft"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Update Vex Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
