---
name: Release Drafter

on:
  push:
    branches: [main]
    paths-ignore:
      - 'vscode-extension/**'
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - 'vscode-extension/**'

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}